INSERT INTO users VALUES (8890, 'heslo', 'heslo', 'ROLE_ADMIN', 'admin');
INSERT INTO users VALUES (8881, 'heslo', 'heslo', 'ROLE_BOARD_MEMBER', 'boardmember');
INSERT INTO users VALUES (8901, 'heslo', 'heslo', 'ROLE_BOARD_MEMBER', 'boardmember2');
INSERT INTO users VALUES (8882, 'heslo', 'heslo', 'ROLE_AUTHOR', 'author');
INSERT INTO users VALUES (8903, 'heslo', 'heslo', 'ROLE_AUTHOR', 'author2');
INSERT INTO users VALUES (8904, 'heslo', 'heslo', 'ROLE_AUTHOR', 'author3');
INSERT INTO users VALUES (8883, 'heslo', 'heslo', 'ROLE_CORRECTOR', 'corrector');
INSERT INTO users VALUES (8905, 'heslo', 'heslo', 'ROLE_CORRECTOR', 'corrector2');
INSERT INTO users VALUES (8906, 'heslo', 'heslo', 'ROLE_CORRECTOR', 'corrector3');
INSERT INTO users VALUES (8907, 'heslo', 'heslo', 'ROLE_CORRECTOR', 'corrector4');
INSERT INTO admin VALUES (8890);
INSERT INTO advisoryboardmember VALUES ('Beta', 'Boardova', 8881);
INSERT INTO advisoryboardmember VALUES ('Branislav', 'Sabol', 8901);
INSERT INTO author VALUES ('Adam', 'Autor', 8882);
INSERT INTO author VALUES ('Alex', 'Adamovic', 8903);
INSERT INTO author VALUES ('Alfonz', 'Mucha', 8904);
INSERT INTO corrector VALUES ('Karol', 'Korektor', 'corrector@corrector.co', 8883);
INSERT INTO corrector VALUES ('Kamil', 'K', 'corrector@corrector.co', 8905);
INSERT INTO corrector VALUES ('Kristína', 'Kováčová', 'corrector@corrector.co', 8906);
INSERT INTO corrector VALUES ('Kristián', 'Kandráč', 'corrector@corrector.co', 8907);